package microservices.com.multiplication.service;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import static org.assertj.core.api.Assertions.assertThat;
import org.junit.Before;
import org.junit.Test;

public class RandomGeneratorServiceImplTest {
    private RandomGeneratorServiceImpl randomGeneratorServiceImpl;
    
    // enable to use a new instance of RandomGeneratorServiceImpl for each test
    @Before
    public void setUp() {
        randomGeneratorServiceImpl = new RandomGeneratorServiceImpl();
    }
    
    @Test
    public void generateRandomFactorBetweenExpectedLimits() throws Exception{
        // we will wan to test if the 1000 random numbers generated by the RandomGeneratorServiceImplementation is between 11 and 100
        // create our list
        List<Integer> randomNumbers = IntStream.range(0, 1000).map(i -> randomGeneratorServiceImpl.generateRandomFactor())
                .boxed().collect(Collectors.toList());

        //print the random numbers
        // System.out.println("Random Numbers: " + randomNumbers);

        // Check if all numbers are between 11 and 100
        assertThat(randomNumbers).containsAnyElementsOf(
                IntStream.range(11, 100).boxed().collect(Collectors.toList())
        );    
    }

}
